version: '3.9'

services: 
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    volumes:
      - mongodb:/data/db
   
  api:
    build: .
    working_dir: /app
    restart: always
     
    ports:
      - 5006:5006
    environment:
     DATABASE: mongodb://mongodb:27017/productService
    depends_on:
      - mongodb

volumes:
 mongodb: {}